### ISSUE TITLE
数据源补全

### ISSUE THREAD

**Issue by zisheng-ai** [warmhug/antd-mobile-demo-data#2]
请求把数据补全

**Comment by warmhug** [comment]
只是 demo 用，为什么要补全？

**Comment by zhuohao1421** [comment]
补全提交了，可以使用起来～

**Comment by zisheng-ai** [comment]
已经两个月过去了，我要是还在等，饭碗早丢了。。我已经提交了一个新的库用于地区选择。同时支持1 2 3 4级选择

**Comment by zisheng-ai** [comment]
已经两个月过去了，我要是还在等，饭碗早丢了。。我已经提交了一个新的库用于地区选择。同时支持1 2 3 4级选择

**Comment by warmhug** [comment]
很抱歉，这只是 demo 不需要补全，建议使用自己的数据。

**Comment by vortesnail** [comment]
> 已经两个月过去了，我要是还在等，饭碗早丢了。。我已经提交了一个新的库用于地区选择。同时支持1 2 3 4级选择

呃，能给下这个库的地址吗，现在很需要呐～

**Comment by zisheng-ai** [comment]
@vortesnail https://github.com/sishuguojixuefu/antd-mobile-area-data
